name: CI - Ruby

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      cache-key: rb-build
      run: bazel build //rb:selenium-devtools //rb:selenium-webdriver

  integration-tests-remote:
    name: Remote Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
        os:
          - windows
    with:
      name: Remote Tests (${{ matrix.browser }}, ${{ matrix.os }})
      browser: ${{ matrix.browser }}
      cache-key: rb-remote-${{ matrix.browser }}-test
      os: ${{ matrix.os }}
      run: >
        bazel test
        --define browser=${{ matrix.browser }}
        --define remote=true
        --flaky_test_attempts 3
        --local_test_jobs 1
        --test_env=DEBUG=1
        //rb/spec/integration/...
